### ISSUE TITLE
Seem not working

### ISSUE THREAD

**Issue by bibifr** [4c65736975/bewareOfStraw#11]
### Version

1.0.1.2

### Game Version

Farming Simulator 22 (1.13.1.1)

### 👣 Steps to reproduce

hello, I wanted to know if some other mods has issue compatibility whit this one, because it's look like not working for me. 

Im it's attaching Log file 

Thanks for any help

### ⭐️ Expected Behavior

[log.txt](https://github.com/VertexFloat/bewareOfStraw/files/14432084/log.txt)

**Comment by 4c65736975** [comment]
Looking at your log, these modifications are giving you a lot of errors, turn them off and try without them.

FS22_PoolDeck,
FS22_WorkshopTrigger2,
Courseplay_FS22,
FS22_DefPack -> I would mainly focus on this one

**Comment by bibifr** [comment]
Well 

Pool deck and workshop has been removed 
Not working

Defpack is removed 
not working

i don't suspect courseplay because i don't use it whit harvester. 
A idea?

**Comment by 4c65736975** [comment]
> Well
> 
> Pool deck and workshop has been removed Not working
> 
> Defpack is removed not working
> 
> i don't suspect courseplay because i don't use it whit harvester. A idea?

For me it will be hard to download all the mods you use to reproduce the problem, try a clean save with only BewareOfStraw and let me know. Some mod must conflict.

**Comment by bibifr** [comment]
It's ok i found the issur it's related to this mod

https://www.farming-simulator.com/mod.php?lang=fr&country=fr&mod_id=228312&title=fs2022

Since i removed it i got not issue anymore 

Thanks for help

**Comment by 4c65736975** [comment]
No problem, I'm glad everything is working properly now, enjoy the game 😉
